package collectors

import (
	"github.com/dimonomid/montray/v2"
	"github.com/dimonomid/montray/v2/logs"
)

type Collector interface {
	// Close tears down the collector. It's synchronous: by the time Close returns,
	// all resources held by the Collector are already reclaimed.
	Close()
}

type Params struct {
	// ID identifies this particular collector. The item keys (montray.ItemKey)
	// generated by this collector must be prefixed with it and a dot.
	ID string

	Logger *logs.Logger

	// UpdatesChan is where the collector should send updates. It's ok to send
	// redundant updates (those that didn't change since the last time).
	UpdatesChan chan<- *Update
}

type Update struct {
	Items map[montray.ItemKey]*montray.Item
	Err   error
}
