# Generated by `montray-server setup`; replaced only with `--reinstall`.
# Use a systemd drop-in for local overrides.
[Unit]
Description=Montray Server: system health monitor
After=network.target

# Montray provides monitoring, so a transient failure or unexpected clean exit
# must not leave it permanently stopped. Retry indefinitely, with RestartSec
# below keeping persistent failures from causing a tight restart loop.
StartLimitIntervalSec=0

[Service]
User=_montray
Group=_montray
ExecStart={{ systemdUnitArgument .Executable }} --config {{ systemdUnitArgument .ConfigFilename }}
Restart=always
RestartSec=10

# Hardening
ProtectSystem=full
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
